import type { Card, Benefit, PurchaseCategory, OfferUpdate, CardSettingDefinition, Bank } from './types'

export const BANKS: Bank[] = [
  { name: 'American Express', issuer_key: 'american_express', gradient: 'from-zinc-700 to-zinc-900' },
  { name: 'Chase',            issuer_key: 'chase',            gradient: 'from-blue-800 to-blue-950' },
  { name: 'Capital One',      issuer_key: 'capital_one',      gradient: 'from-red-800 to-red-950'   },
  { name: 'Bank of America',  issuer_key: 'bank_of_america',  gradient: 'from-red-900 to-slate-900' },
  { name: 'Citi',             issuer_key: 'citi',             gradient: 'from-blue-600 to-blue-800' },
  { name: 'Discover',         issuer_key: 'discover',         gradient: 'from-orange-600 to-amber-700' },
  { name: 'Wells Fargo',      issuer_key: 'wells_fargo',      gradient: 'from-red-600 to-red-800'   },
  { name: 'Apple',            issuer_key: 'apple',            gradient: 'from-slate-600 to-slate-800' },
]

export const CARDS: Card[] = [
  // ── American Express ─────────────────────────────────────────────────────
  {
    card_id: 'amex_gold',
    issuer: 'American Express',
    card_name: 'American Express Gold Card',
    annual_fee: 325,
    card_type: 'charge',
    reward_summary: '4x dining & U.S. supermarkets, 3x flights, 2x other travel',
    reward_notes: 'Strong dining and U.S. supermarket rewards; multiple monthly and semiannual credits',
    requires_user_settings: false,
  },
  {
    card_id: 'amex_platinum',
    issuer: 'American Express',
    card_name: 'American Express Platinum Card',
    annual_fee: 695,
    card_type: 'charge',
    reward_summary: '5x flights/prepaid hotels via Amex Travel; extensive travel credits',
    reward_notes: 'Premium travel card with $200 hotel credit, $200 airline fee credit, $240 digital entertainment, lounge access',
    requires_user_settings: false,
  },
  {
    card_id: 'amex_blue_cash_preferred',
    issuer: 'American Express',
    card_name: 'Blue Cash Preferred Card',
    annual_fee: 95,
    card_type: 'credit',
    reward_summary: '6% U.S. supermarkets (up to $6k/yr), 6% select U.S. streaming, 3% transit & U.S. gas stations',
    reward_notes: 'Best-in-class for U.S. supermarkets and streaming; flat 3% on transit and gas',
    requires_user_settings: false,
  },
  // ── Chase ─────────────────────────────────────────────────────────────────
  {
    card_id: 'chase_sapphire_preferred',
    issuer: 'Chase',
    card_name: 'Chase Sapphire Preferred',
    annual_fee: 95,
    card_type: 'credit',
    reward_summary: '3x dining, 5x Lyft (through Mar 2025), 2x travel; transfer partners; $50 annual hotel credit',
    reward_notes: 'Strong travel and dining rewards; transfer partners; annual hotel credit',
    requires_user_settings: false,
  },
  {
    card_id: 'chase_sapphire_reserve',
    issuer: 'Chase',
    card_name: 'Chase Sapphire Reserve',
    annual_fee: 550,
    card_type: 'credit',
    reward_summary: '3x dining & travel, $300 annual travel credit, Priority Pass lounge access, $100 TSA PreCheck/Global Entry',
    reward_notes: 'Premium travel card; $300 travel credit; lounge access; best-in-class transfer partners',
    requires_user_settings: false,
  },
  {
    card_id: 'chase_freedom_flex',
    issuer: 'Chase',
    card_name: 'Chase Freedom Flex',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '5% rotating quarterly categories (up to $1,500), 5% Chase Travel, 3% dining & drugstores, 1% else',
    reward_notes: 'Rotating 5% quarterly categories; strong fixed rewards on dining and drugstores',
    requires_user_settings: true,
  },
  {
    card_id: 'chase_freedom_unlimited',
    issuer: 'Chase',
    card_name: 'Chase Freedom Unlimited',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '1.5% on everything, 3% dining & drugstores, 5% Chase Travel',
    reward_notes: 'Solid flat-rate earner; great for non-category spend when paired with Sapphire cards',
    requires_user_settings: false,
  },
  // ── Capital One ───────────────────────────────────────────────────────────
  {
    card_id: 'capital_one_savor',
    issuer: 'Capital One',
    card_name: 'Capital One Savor',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '3% dining, groceries, entertainment & streaming; 8% Capital One Entertainment',
    reward_notes: 'Cash back card for dining, groceries, entertainment, streaming, Capital One Entertainment, and Capital One Travel',
    requires_user_settings: false,
  },
  {
    card_id: 'capital_one_venture_x',
    issuer: 'Capital One',
    card_name: 'Capital One Venture X',
    annual_fee: 395,
    card_type: 'credit',
    reward_summary: '2x on everything, 5x hotels & rental cars via Capital One Travel, 10x flights via Capital One Travel; $300 annual travel credit; 10k anniversary miles',
    reward_notes: 'Premium travel card; $300 annual travel credit offsets fee; 10k anniversary miles; lounge access',
    requires_user_settings: false,
  },
  {
    card_id: 'capital_one_quicksilver',
    issuer: 'Capital One',
    card_name: 'Capital One Quicksilver',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '1.5% cash back on everything, 5% on hotels & rental cars via Capital One Travel',
    reward_notes: 'Simple flat-rate cash back card; no annual fee; easy redemption',
    requires_user_settings: false,
  },
  // ── Bank of America ───────────────────────────────────────────────────────
  {
    card_id: 'boa_customized_cash',
    issuer: 'Bank of America',
    card_name: 'Bank of America Customized Cash Rewards',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '3% on your chosen category (changeable monthly), 2% at grocery stores & wholesale clubs, 1% elsewhere',
    reward_notes: 'Selectable 3% category that can be changed once per calendar month',
    requires_user_settings: true,
  },
  // ── Citi ──────────────────────────────────────────────────────────────────
  {
    card_id: 'citi_custom_cash',
    issuer: 'Citi',
    card_name: 'Citi Custom Cash Card',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '5% cash back automatically on your top eligible spend category each billing cycle (up to $500), 1% elsewhere',
    reward_notes: 'Automatically earns 5% on your top eligible spend category each billing cycle — no selection needed',
    requires_user_settings: false,
  },
  {
    card_id: 'citi_double_cash',
    issuer: 'Citi',
    card_name: 'Citi Double Cash Card',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '2% cash back on all purchases (1% when you buy, 1% when you pay)',
    reward_notes: 'Industry-standard flat-rate card; 2% on everything with no category restrictions',
    requires_user_settings: false,
  },
  // ── Discover ──────────────────────────────────────────────────────────────
  {
    card_id: 'discover_it',
    issuer: 'Discover',
    card_name: 'Discover it Cash Back',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '5% rotating quarterly categories (up to $1,500/quarter after activation), 1% everywhere else',
    reward_notes: 'Rotating 5% quarterly categories; cash back match first year',
    requires_user_settings: true,
  },
  // ── Wells Fargo ───────────────────────────────────────────────────────────
  {
    card_id: 'wells_fargo_active_cash',
    issuer: 'Wells Fargo',
    card_name: 'Wells Fargo Active Cash Card',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '2% cash rewards on all purchases',
    reward_notes: 'Simple 2% flat-rate cash rewards card; no annual fee; $200 cash rewards sign-up bonus',
    requires_user_settings: false,
  },
  // ── Apple ─────────────────────────────────────────────────────────────────
  {
    card_id: 'apple_card',
    issuer: 'Apple',
    card_name: 'Apple Card',
    annual_fee: 0,
    card_type: 'credit',
    reward_summary: '3% at Apple and select partners, 2% via Apple Pay, 1% physical card',
    reward_notes: 'Best used via Apple Pay; 3% Daily Cash at Apple, T-Mobile, Nike, Walgreens, and more',
    requires_user_settings: false,
  },
]

export const CARD_SETTINGS_DEFINITIONS: CardSettingDefinition[] = [
  {
    card_id: 'boa_customized_cash',
    setting_key: 'selected_category',
    label: '3% Cash Back Category',
    description: 'Choose which category earns 3% cash back. You can change this once per calendar month via the BofA website or app.',
    type: 'select',
    required: true,
    options: [
      { value: 'gas',              label: 'Gas and EV charging' },
      { value: 'online_shopping',  label: 'Online shopping' },
      { value: 'dining',           label: 'Dining' },
      { value: 'travel',           label: 'Travel' },
      { value: 'drug_stores',      label: 'Drug stores and pharmacies' },
      { value: 'home_improvement', label: 'Home improvement and furnishings' },
    ],
    reminder_text: 'Review your Bank of America 3% category before the month ends to maximize rewards.',
  },
  {
    card_id: 'chase_freedom_flex',
    setting_key: 'quarterly_activated',
    label: 'Q2 2026 5% Category Activated',
    description: 'Activate the quarterly 5% bonus category each quarter to earn the elevated rate.',
    type: 'boolean',
    required: false,
    reminder_text: 'Activate your Chase Freedom Flex quarterly category to earn 5% cash back.',
  },
  {
    card_id: 'discover_it',
    setting_key: 'quarterly_activated',
    label: 'Q2 2026 5% Category Activated',
    description: 'Activate the quarterly 5% bonus category each quarter to earn the elevated rate.',
    type: 'boolean',
    required: false,
    reminder_text: 'Activate your Discover it quarterly category to earn 5% cash back.',
  },
]

export const BENEFITS: Benefit[] = [
  // ── Amex Gold ─────────────────────────────────────────────────────────────
  {
    benefit_id: 'amex_uber_monthly',
    card_id: 'amex_gold',
    benefit_name: 'Uber Cash',
    benefit_type: 'statement_credit',
    value_amount: '10',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Uber and Uber Eats',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'User must add eligible Amex Gold to Uber account. Monthly value expires if unused.',
  },
  {
    benefit_id: 'amex_dunkin_monthly',
    card_id: 'amex_gold',
    benefit_name: "Dunkin' Credit",
    benefit_type: 'statement_credit',
    value_amount: '7',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: "U.S. Dunkin' locations",
    requires_enrollment: true,
    source_type: 'official',
    notes: "Earn up to $7 in monthly statement credits after eligible payment.",
  },
  {
    benefit_id: 'amex_dining_monthly',
    card_id: 'amex_gold',
    benefit_name: 'Dining Credit',
    benefit_type: 'statement_credit',
    value_amount: '10',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Eligible dining partners',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Monthly dining statement credit at eligible partners.',
  },
  {
    benefit_id: 'amex_resy_semiannual',
    card_id: 'amex_gold',
    benefit_name: 'Resy Credit',
    benefit_type: 'statement_credit',
    value_amount: '50',
    frequency: 'semiannual',
    reset_rule: 'jan_jun_and_jul_dec',
    deadline_type: 'period_end',
    merchant_restriction: 'Eligible U.S. Resy restaurants',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Up to $50 semi-annually after enrollment and eligible purchase.',
  },
  // ── Amex Platinum ─────────────────────────────────────────────────────────
  {
    benefit_id: 'amex_plat_hotel_annual',
    card_id: 'amex_platinum',
    benefit_name: '$200 Hotel Credit',
    benefit_type: 'statement_credit',
    value_amount: '200',
    frequency: 'annual',
    reset_rule: 'calendar_year',
    deadline_type: 'year_end',
    merchant_restriction: 'Prepaid Fine Hotels + Resorts or The Hotel Collection via Amex Travel (min 2-night stay)',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Must book through the Amex Travel portal as a prepaid stay.',
  },
  {
    benefit_id: 'amex_plat_airline_annual',
    card_id: 'amex_platinum',
    benefit_name: '$200 Airline Fee Credit',
    benefit_type: 'statement_credit',
    value_amount: '200',
    frequency: 'annual',
    reset_rule: 'calendar_year',
    deadline_type: 'year_end',
    merchant_restriction: 'One selected airline',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Select one qualifying airline per year. Covers incidental fees (baggage, seat upgrades). Not airfare.',
  },
  {
    benefit_id: 'amex_plat_digital_monthly',
    card_id: 'amex_platinum',
    benefit_name: 'Digital Entertainment Credit',
    benefit_type: 'statement_credit',
    value_amount: '20',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Eligible streaming and digital services (Disney+, Hulu, ESPN+, Peacock, Audible, SiriusXM, NY Times, WSJ)',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Up to $20/month. Must enroll via Amex account. Up to $240/year.',
  },
  // ── Amex Blue Cash Preferred ──────────────────────────────────────────────
  {
    benefit_id: 'amex_bcp_disney_monthly',
    card_id: 'amex_blue_cash_preferred',
    benefit_name: 'Disney Bundle Credit',
    benefit_type: 'statement_credit',
    value_amount: '7',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Disney Bundle (Disney+, Hulu, ESPN+)',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Up to $7/month statement credit when you pay for the Disney Bundle. Enrollment required.',
  },
  {
    benefit_id: 'amex_bcp_equinox_monthly',
    card_id: 'amex_blue_cash_preferred',
    benefit_name: 'Equinox+ Credit',
    benefit_type: 'statement_credit',
    value_amount: '10',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Equinox+ digital fitness subscription',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Up to $10/month credit toward Equinox+ subscription after enrollment.',
  },
  // ── Chase Sapphire Reserve ────────────────────────────────────────────────
  {
    benefit_id: 'csr_travel_annual',
    card_id: 'chase_sapphire_reserve',
    benefit_name: '$300 Annual Travel Credit',
    benefit_type: 'statement_credit',
    value_amount: '300',
    frequency: 'annual',
    reset_rule: 'card_anniversary',
    deadline_type: 'anniversary',
    merchant_restriction: 'Broad travel purchases (airlines, hotels, car rentals, taxis, trains, etc.)',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Automatically applied to the first $300 in travel purchases each cardmember year. Very broad travel category.',
  },
  // ── Chase Sapphire Preferred ──────────────────────────────────────────────
  {
    benefit_id: 'chase_hotel_annual',
    card_id: 'chase_sapphire_preferred',
    benefit_name: 'Annual Hotel Credit',
    benefit_type: 'statement_credit',
    value_amount: '50',
    frequency: 'annual',
    reset_rule: 'card_anniversary',
    deadline_type: 'anniversary',
    merchant_restriction: 'Hotels booked through Chase Travel',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Up to $50 annual credit on hotels booked through Chase Travel portal.',
  },
  // ── Chase Freedom Flex ────────────────────────────────────────────────────
  {
    benefit_id: 'chase_freedom_flex_q2',
    card_id: 'chase_freedom_flex',
    benefit_name: 'Q2 Rotating 5% Category',
    benefit_type: 'reward_multiplier',
    value_amount: 'varies',
    frequency: 'quarterly',
    reset_rule: 'calendar_quarter',
    deadline_type: 'quarter_end',
    merchant_restriction: 'See Chase website for current quarter categories',
    requires_enrollment: true,
    requires_user_setting: true,
    user_setting_key: 'quarterly_activated',
    source_type: 'official',
    notes: 'Activate each quarter to earn 5% on rotating categories (up to $1,500 per quarter).',
  },
  // ── Capital One Venture X ─────────────────────────────────────────────────
  {
    benefit_id: 'venture_x_travel_annual',
    card_id: 'capital_one_venture_x',
    benefit_name: '$300 Annual Travel Credit',
    benefit_type: 'statement_credit',
    value_amount: '300',
    frequency: 'annual',
    reset_rule: 'card_anniversary',
    deadline_type: 'anniversary',
    merchant_restriction: 'Bookings through Capital One Travel portal',
    requires_enrollment: false,
    source_type: 'official',
    notes: '$300 credit for bookings made through the Capital One Travel portal each year.',
  },
  {
    benefit_id: 'venture_x_anniversary_miles',
    card_id: 'capital_one_venture_x',
    benefit_name: '10,000 Anniversary Miles',
    benefit_type: 'other',
    value_amount: '100',
    frequency: 'annual',
    reset_rule: 'card_anniversary',
    deadline_type: 'anniversary',
    merchant_restriction: 'Automatic on cardmember anniversary',
    requires_enrollment: false,
    source_type: 'official',
    notes: '10,000 bonus miles (worth ~$100 in travel) deposited each year on account anniversary.',
  },
  // ── Capital One Offers ────────────────────────────────────────────────────
  {
    benefit_id: 'capital_one_offers',
    card_id: 'capital_one_savor',
    benefit_name: 'Capital One Offers',
    benefit_type: 'merchant_offer',
    value_amount: 'varies',
    frequency: 'offer_based',
    reset_rule: 'offer_deadline',
    deadline_type: 'custom',
    merchant_restriction: 'Participating retailers',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Cardholders can access offers for rewards or statement credits.',
  },
  // ── Bank of America ───────────────────────────────────────────────────────
  {
    benefit_id: 'boa_category_change',
    card_id: 'boa_customized_cash',
    benefit_name: 'Monthly Category Change',
    benefit_type: 'category_optimization',
    value_amount: '0',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Online Banking or Mobile Banking',
    requires_enrollment: false,
    requires_user_setting: true,
    user_setting_key: 'selected_category',
    source_type: 'official',
    notes: 'Change selected 3% category once per calendar month.',
  },
  {
    benefit_id: 'boa_bankamerideals',
    card_id: 'boa_customized_cash',
    benefit_name: 'BankAmeriDeals',
    benefit_type: 'merchant_offer',
    value_amount: 'varies',
    frequency: 'offer_based',
    reset_rule: 'offer_deadline',
    deadline_type: 'custom',
    merchant_restriction: 'Participating merchants',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'User must pick deals, shop, and pay with eligible card.',
  },
  // ── Discover it ───────────────────────────────────────────────────────────
  {
    benefit_id: 'discover_rotating_q2',
    card_id: 'discover_it',
    benefit_name: 'Q2 Rotating 5% Category',
    benefit_type: 'reward_multiplier',
    value_amount: 'varies',
    frequency: 'quarterly',
    reset_rule: 'calendar_quarter',
    deadline_type: 'quarter_end',
    merchant_restriction: 'See Discover website for current quarter categories',
    requires_enrollment: true,
    requires_user_setting: true,
    user_setting_key: 'quarterly_activated',
    source_type: 'official',
    notes: 'Activate quarterly to earn 5% cash back in rotating categories (up to $1,500 per quarter).',
  },
]

export const PURCHASE_CATEGORIES: PurchaseCategory[] = [
  { category: 'dining',          preferred_card_id: 'amex_gold',                reason: 'Amex Gold earns 4x at restaurants. Check if a monthly dining credit partner applies first.' },
  { category: 'dining',          preferred_card_id: 'chase_sapphire_reserve',   reason: 'Chase Sapphire Reserve earns 3x on dining with flexible point transfers.' },
  { category: 'dining',          preferred_card_id: 'chase_sapphire_preferred', reason: 'Chase Sapphire Preferred earns 3x on dining.' },
  { category: 'dining',          preferred_card_id: 'capital_one_savor',        reason: 'Capital One Savor earns 3% on dining.' },
  { category: 'dining',          preferred_card_id: 'chase_freedom_flex',       reason: 'Chase Freedom Flex earns 3% on dining, or 5% if dining is a rotating quarter category.' },
  { category: 'dining',          preferred_card_id: 'citi_custom_cash',         reason: 'Citi Custom Cash automatically gives 5% if dining is your top spend category.' },

  { category: 'groceries',       preferred_card_id: 'amex_blue_cash_preferred', reason: 'Blue Cash Preferred earns 6% at U.S. supermarkets (up to $6k/yr) — best rate available.' },
  { category: 'groceries',       preferred_card_id: 'amex_gold',                reason: 'Amex Gold earns 4x at U.S. supermarkets. Category may not apply to warehouse clubs or delivery apps.' },
  { category: 'groceries',       preferred_card_id: 'capital_one_savor',        reason: 'Capital One Savor earns 3% at grocery stores.' },

  { category: 'entertainment',   preferred_card_id: 'capital_one_savor',        reason: 'Capital One Savor earns 3% on entertainment, including concerts, sporting events, and attractions.' },
  { category: 'entertainment',   preferred_card_id: 'chase_freedom_flex',       reason: 'Chase Freedom Flex may earn 5% if entertainment is a rotating quarter category.' },

  { category: 'streaming',       preferred_card_id: 'amex_blue_cash_preferred', reason: 'Blue Cash Preferred earns 6% on select U.S. streaming services.' },
  { category: 'streaming',       preferred_card_id: 'capital_one_savor',        reason: 'Capital One Savor earns 3% on popular streaming services.' },
  { category: 'streaming',       preferred_card_id: 'amex_platinum',            reason: 'Amex Platinum offers a $20/month digital entertainment credit for eligible streaming services.' },

  { category: 'online shopping', preferred_card_id: 'boa_customized_cash',      reason: 'Bank of America Customized Cash earns 3% on online shopping if that category is selected.' },
  { category: 'online shopping', preferred_card_id: 'citi_custom_cash',         reason: 'Citi Custom Cash automatically gives 5% if online shopping is your top spend category.' },
  { category: 'online shopping', preferred_card_id: 'chase_freedom_flex',       reason: 'Chase Freedom Flex may earn 5% on Amazon or other online shopping in rotating quarters.' },

  { category: 'gas',             preferred_card_id: 'amex_blue_cash_preferred', reason: 'Blue Cash Preferred earns 3% at U.S. gas stations.' },
  { category: 'gas',             preferred_card_id: 'boa_customized_cash',      reason: 'Bank of America Customized Cash earns 3% on gas and EV charging if that category is selected.' },
  { category: 'gas',             preferred_card_id: 'citi_custom_cash',         reason: 'Citi Custom Cash automatically gives 5% if gas is your top spend category.' },
  { category: 'gas',             preferred_card_id: 'chase_freedom_flex',       reason: 'Chase Freedom Flex may earn 5% at gas stations in rotating quarters.' },

  { category: 'travel',          preferred_card_id: 'chase_sapphire_reserve',   reason: 'Chase Sapphire Reserve earns 3x on travel with the broadest definition of travel spend.' },
  { category: 'travel',          preferred_card_id: 'capital_one_venture_x',    reason: 'Capital One Venture X earns 5x on hotels/rentals and 10x on flights via Capital One Travel.' },
  { category: 'travel',          preferred_card_id: 'chase_sapphire_preferred', reason: 'Chase Sapphire Preferred earns 2x on travel with strong transfer partners.' },
  { category: 'travel',          preferred_card_id: 'amex_platinum',            reason: 'Amex Platinum earns 5x on flights and prepaid hotels booked through Amex Travel.' },
  { category: 'travel',          preferred_card_id: 'boa_customized_cash',      reason: 'Bank of America Customized Cash earns 3% on travel if that category is selected.' },

  { category: 'drugstores',      preferred_card_id: 'chase_freedom_flex',       reason: 'Chase Freedom Flex earns 3% at drugstores year-round.' },
  { category: 'drugstores',      preferred_card_id: 'chase_freedom_unlimited',  reason: 'Chase Freedom Unlimited earns 3% at drugstores year-round.' },
  { category: 'drugstores',      preferred_card_id: 'boa_customized_cash',      reason: 'Bank of America Customized Cash earns 3% at drug stores if that category is selected.' },
]

export const SEED_OFFER_UPDATES: OfferUpdate[] = [
  {
    update_id: 'sample_001',
    issuer: 'American Express',
    card_name: 'American Express Gold Card',
    title: 'Sample restaurant offer',
    description: 'Spend $100 and get $20 back at selected restaurants. Enrollment required.',
    deadline: '2026-06-30',
    requires_enrollment: true,
    status: 'active',
  },
  {
    update_id: 'sample_002',
    issuer: 'Bank of America',
    card_name: 'Bank of America Customized Cash Rewards',
    title: 'Sample BankAmeriDeal',
    description: 'Earn 10% cash back at a selected merchant after activating the deal.',
    deadline: '2026-05-31',
    requires_enrollment: false,
    status: 'active',
  },
]
