import type { Card, Benefit, PurchaseCategory, OfferUpdate } from './types'

export const CARDS: Card[] = [
  {
    card_id: 'amex_gold',
    issuer: 'American Express',
    card_name: 'American Express Gold Card',
    annual_fee: 325,
    reward_notes: 'Strong dining and U.S. supermarket rewards; multiple monthly and semiannual credits',
  },
  {
    card_id: 'capital_one_savor',
    issuer: 'Capital One',
    card_name: 'Capital One Savor',
    annual_fee: 0,
    reward_notes: 'Cash back card for dining, groceries, entertainment, streaming, Capital One Entertainment, and Capital One Travel',
  },
  {
    card_id: 'boa_customized_cash',
    issuer: 'Bank of America',
    card_name: 'Bank of America Customized Cash Rewards',
    annual_fee: 0,
    reward_notes: 'Selectable 3% category that can be changed once per calendar month',
  },
  {
    card_id: 'chase_sapphire_preferred',
    issuer: 'Chase',
    card_name: 'Chase Sapphire Preferred',
    annual_fee: 95,
    reward_notes: 'Strong travel and dining rewards; transfer partners; annual hotel credit',
  },
  {
    card_id: 'discover_it',
    issuer: 'Discover',
    card_name: 'Discover it Cash Back',
    annual_fee: 0,
    reward_notes: 'Rotating 5% quarterly categories; cash back match first year',
  },
]

export const BENEFITS: Benefit[] = [
  {
    benefit_id: 'amex_uber_monthly',
    card_id: 'amex_gold',
    benefit_name: 'Uber Cash',
    benefit_type: 'statement_credit',
    value_amount: '10',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Uber and Uber Eats',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'User must add eligible Amex Gold to Uber account. Monthly value expires if unused.',
  },
  {
    benefit_id: 'amex_dunkin_monthly',
    card_id: 'amex_gold',
    benefit_name: "Dunkin' Credit",
    benefit_type: 'statement_credit',
    value_amount: '7',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: "U.S. Dunkin' locations",
    requires_enrollment: true,
    source_type: 'official',
    notes: "Earn up to $7 in monthly statement credits after eligible payment.",
  },
  {
    benefit_id: 'amex_dining_monthly',
    card_id: 'amex_gold',
    benefit_name: 'Dining Credit',
    benefit_type: 'statement_credit',
    value_amount: '10',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Eligible dining partners',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Monthly dining statement credit at eligible partners.',
  },
  {
    benefit_id: 'amex_resy_semiannual',
    card_id: 'amex_gold',
    benefit_name: 'Resy Credit',
    benefit_type: 'statement_credit',
    value_amount: '50',
    frequency: 'semiannual',
    reset_rule: 'jan_jun_and_jul_dec',
    deadline_type: 'period_end',
    merchant_restriction: 'Eligible U.S. Resy restaurants',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Up to $50 semi-annually after enrollment and eligible purchase.',
  },
  {
    benefit_id: 'boa_category_change',
    card_id: 'boa_customized_cash',
    benefit_name: 'Monthly Category Change',
    benefit_type: 'category_optimization',
    value_amount: '0',
    frequency: 'monthly',
    reset_rule: 'calendar_month',
    deadline_type: 'month_end',
    merchant_restriction: 'Online Banking or Mobile Banking',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Change selected 3% category once per calendar month.',
  },
  {
    benefit_id: 'boa_bankamerideals',
    card_id: 'boa_customized_cash',
    benefit_name: 'BankAmeriDeals',
    benefit_type: 'merchant_offer',
    value_amount: 'varies',
    frequency: 'offer_based',
    reset_rule: 'offer_deadline',
    deadline_type: 'custom',
    merchant_restriction: 'Participating merchants',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'User must pick deals, shop, and pay with eligible card.',
  },
  {
    benefit_id: 'capital_one_offers',
    card_id: 'capital_one_savor',
    benefit_name: 'Capital One Offers',
    benefit_type: 'merchant_offer',
    value_amount: 'varies',
    frequency: 'offer_based',
    reset_rule: 'offer_deadline',
    deadline_type: 'custom',
    merchant_restriction: 'Participating retailers',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Cardholders can access offers for rewards or statement credits.',
  },
  {
    benefit_id: 'chase_hotel_annual',
    card_id: 'chase_sapphire_preferred',
    benefit_name: 'Annual Hotel Credit',
    benefit_type: 'statement_credit',
    value_amount: '50',
    frequency: 'annual',
    reset_rule: 'card_anniversary',
    deadline_type: 'anniversary',
    merchant_restriction: 'Hotels booked through Chase Travel',
    requires_enrollment: false,
    source_type: 'official',
    notes: 'Up to $50 annual credit on hotels booked through Chase Travel portal.',
  },
  {
    benefit_id: 'discover_rotating_q2',
    card_id: 'discover_it',
    benefit_name: 'Q2 Rotating 5% Category',
    benefit_type: 'reward_multiplier',
    value_amount: 'varies',
    frequency: 'quarterly',
    reset_rule: 'calendar_quarter',
    deadline_type: 'quarter_end',
    merchant_restriction: 'See Discover website for current quarter categories',
    requires_enrollment: true,
    source_type: 'official',
    notes: 'Activate quarterly to earn 5% cash back in rotating categories (up to $1,500 per quarter).',
  },
]

export const PURCHASE_CATEGORIES: PurchaseCategory[] = [
  {
    category: 'dining',
    preferred_card_id: 'amex_gold',
    reason: 'Amex Gold earns strong rewards at restaurants. Check if a monthly dining credit partner applies first.',
  },
  {
    category: 'groceries',
    preferred_card_id: 'amex_gold',
    reason: 'Amex Gold is strong for U.S. supermarkets. Category coding may vary for delivery apps.',
  },
  {
    category: 'entertainment',
    preferred_card_id: 'capital_one_savor',
    reason: 'Capital One Savor earns elevated rewards on entertainment purchases.',
  },
  {
    category: 'streaming',
    preferred_card_id: 'capital_one_savor',
    reason: 'Capital One Savor is strong for popular streaming services.',
  },
  {
    category: 'online shopping',
    preferred_card_id: 'boa_customized_cash',
    reason: 'Bank of America Customized Cash may be useful if online shopping is selected as the 3% category.',
  },
  {
    category: 'gas',
    preferred_card_id: 'boa_customized_cash',
    reason: 'Bank of America Customized Cash may be useful if gas or EV charging is selected as the 3% category.',
  },
  {
    category: 'travel',
    preferred_card_id: 'chase_sapphire_preferred',
    reason: 'Chase Sapphire Preferred earns strong travel rewards and has valuable transfer partners.',
  },
]

export const SEED_OFFER_UPDATES: OfferUpdate[] = [
  {
    update_id: 'sample_001',
    issuer: 'American Express',
    card_name: 'American Express Gold Card',
    title: 'Sample restaurant offer',
    description: 'Spend $100 and get $20 back at selected restaurants. Enrollment required.',
    deadline: '2026-06-30',
    requires_enrollment: true,
    status: 'active',
  },
  {
    update_id: 'sample_002',
    issuer: 'Bank of America',
    card_name: 'Bank of America Customized Cash Rewards',
    title: 'Sample BankAmeriDeal',
    description: 'Earn 10% cash back at a selected merchant after activating the deal.',
    deadline: '2026-05-31',
    requires_enrollment: false,
    status: 'active',
  },
]
